include_guard()

include(${CMAKE_CURRENT_LIST_DIR}/AugrRack.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Augite.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImPlot.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImNodes.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImKnobs.cmake)

function(USES_AUGITE_VIEWER THIS)
  USES_AUGR_RACK(${THIS})
  USES_AUGITE(${THIS})
  USES_IMPLOT(${THIS})
  USES_IMNODES(${THIS})
  USES_IMKNOBS(${THIS})
  target_link_libraries(${THIS} PRIVATE AugiteViewer)
endfunction()
