include_guard()

include(${CMAKE_CURRENT_LIST_DIR}/StdUuid.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Fmt.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/SpdLog.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Json.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/XTensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/KissFft.cmake)

function(INTERNAL_AUGR_CORE THIS)
  USES_STDUUID(${THIS})
  USES_FMT(${THIS})
  USES_SPDLOG(${THIS})
  USES_JSON(${THIS})
  USES_XTENSOR(${THIS})
  USES_KISSFFT(${THIS})
  target_include_directories(${THIS} PRIVATE ${AUGR_CORE_ROOT}/include)
endfunction()

function(USES_AUGR_CORE THIS)
  INTERNAL_AUGR_CORE(${THIS})
  target_link_libraries(${THIS} PRIVATE AugrCore)
  target_compile_definitions(${THIS} PRIVATE "NOMINMAX")
endfunction()
