include_guard()

include(${CMAKE_CURRENT_LIST_DIR}/Augr.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Augite.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImGui.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Sdl.cmake)

if(${SHELL_PLATFORM} STREQUAL "Windows")
    set(SHELL_HEADER "<augite/shell/platform/windows/win32_window.h>")
    set(SHELL_CLASS "Win32Window")
elseif(${SHELL_PLATFORM} STREQUAL "X11")
    set(SHELL_HEADER "<augite/shell/platform/x11/x11_window.h>")
    set(SHELL_CLASS "X11Window")
endif()

function(USES_SHELL THIS)
USES_AUGR(${THIS})
USES_AUGITE(${THIS})
USES_IMGUI(${THIS})
USES_SDL(${THIS})
target_compile_definitions(${THIS} PRIVATE SHELL_HEADER=${SHELL_HEADER} SHELL_CLASS=${SHELL_CLASS})
target_include_directories(${THIS} PRIVATE ${AUGR_ROOT}/src)
target_link_libraries(${THIS} PRIVATE ImGui AugiteShell${SHELL_PLATFORM})
endfunction()
