include_guard()

include(${CMAKE_CURRENT_LIST_DIR}/Augr.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Augite.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImPlot.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImNodes.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImKnobs.cmake)

function(USES_VIEW THIS)
  USES_AUGR(${THIS})
  USES_AUGITE(${THIS})
  USES_IMPLOT(${THIS})
  USES_IMNODES(${THIS})
  USES_IMKNOBS(${THIS})
  target_link_libraries(${THIS} PRIVATE AugiteView)
endfunction()
